---
apiVersion: v1
kind: Namespace
metadata:
  name: k8sdev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdev
  namespace: k8sdev
spec:
  selector:
    matchLabels:
      app: k8sdev
  template:
    metadata:
      labels:
        app: k8sdev
    spec:
      initContainers:
        - name: rclone169
          image: docker.io/library/rclone169:latest
          imagePullPolicy: Never
          restartPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
          env:
            - name: LOCAL_PATH
              value: mymac:/Users/mymacuser/absolutepath
            - name: REMOTE_PATH
              value: /app/mnt
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "fusermount3 -uz /app/mnt"]
          volumeMounts:
            - name: app
              mountPath: /app/mnt
              mountPropagation: Bidirectional
            - name: rclone-conf-copy-dir
              mountPath: /root/.config/rclone
            - name: rclone-conf-config-map-dir
              mountPath: /config/rclone
            - name: ssh-config
              mountPath: /root/.ssh
      containers:
        - name: alpine321
          image: docker.io/library/alpine321:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 300Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 200m
          volumeMounts:
            - name: app
              mountPath: /app/mnt
              mountPropagation: HostToContainer
            - name: rclone-conf-config-map-dir
              mountPath: /config/rclone
            - name: ssh-config
              mountPath: /root/.ssh
              readOnly: true
      volumes:
        - name: app
          emptyDir: {}
        - name: rclone-conf-copy-dir
          emptyDir: {}
        - name: rclone-conf-config-map-dir
          configMap:
            name: rclone-config-map
        - name: ssh-config
          secret:
            secretName: ssh-secret
            items:
              - key: ssh-config
                path: config
                mode: 0o600
              - key: ssh-privatekey
                path: id_ed25519
                mode: 0o400
              - key: ssh-publickey
                path: id_ed25519.pub
                mode: 0o644
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config-map
  namespace: k8sdev
data:
  rclone.conf: |
    [mymac]
    type = sftp
    user = mymacuser
    host = 192.168.1.100
    port = 22
    key_file = /root/.ssh/id_ed25519
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
  namespace: k8sdev
type: Opaque
data:
  ssh-config: SG9zdCAqCiAgU3RyaWN0SG9zdEtleUNoZWNraW5nIG5v
  ssh-privatekey: base64-privatekey
  ssh-publickey: base64-publickey
